### ISSUE TITLE
[Feature Request] UpdateTOC

### ISSUE THREAD

**Issue by vinoff** [richardbizik/nvim-toc#1]
It would be nice if there was an option to UpdateTOC, instead of adding a new one. Sure, it doesn't take much to just delete the TOC and create a new one, but it would be even faster if one could just UpdateTOC instead.

**Comment by richardbizik** [comment]
I was thinking about this as well...I will look into it when I have some spare time.

**Comment by vinoff** [comment]
How does this work? I just tried :TOC and couldnt make it update instead of adding a new one.

**Comment by richardbizik** [comment]
It looks for a section that starts with `# Table of contents` or your configured header with
```lua
require("nvim-toc").setup({
  toc_header = "My table of contents"
})
```
and if there is anything present, replaces the current section with regenerated one. If it does not find that section it generates a new one.
Try to pull again. One line was left behind in the commit.
And if the issue persists please send me a simplified markdown with the issue.
