### ISSUE TITLE
Many bugs in TOC linking.

### ISSUE THREAD

**Issue by vinoff** [richardbizik/nvim-toc#2]
You cannot have some characters in the TOC links, it breaks the linking part. For example:

`# This is a question?`

Using your extension becomes:

`1.  [Is this a question?](#Is-this-a-question?)`

That will not properly link you. You have to remove the question mark in the link part.

This is also true for "(", ")", etc..

**Comment by vinoff** [comment]
Also true for "/".

**Comment by richardbizik** [comment]
As far as I am aware there is no silver bullet for header link "sanitization" as this is mostly implementation specific for the UI that renders the markdown file.

**Comment by vinoff** [comment]
> As far as I am aware there is no silver bullet for header link "sanitization" as this is mostly implementation specific for the UI that renders the markdown file.

That is interesting. I only tried in a Hugo blog.
