### ISSUE TITLE
[Feature] Have an equivalent non-numbered list

### ISSUE THREAD

**Issue by GLaDOS-418** [richardbizik/nvim-toc#3]
```md
# H1
## H2a
### H3a
## H2b
### H3b
```

should generate:

```md
- H1
    - H2a
        - H3a
    - H2b 
        - H3b
```

instead of:

```md
1. H1
    1. H2a
        1. H3a
    2. H2b 
        1. H3b
```

maybe `:TOC` can generate numbered list (for backward compatibility) and `:TOCList` (or something better) can generate unnumbereed list.

**Comment by richardbizik** [comment]
Try to pull new changes...there is a new command `:TOCList`. With previous changes you can now update an existing table to an unordered list just by using `:TOCList` or switch back to ordered by using `:TOC`
